replicaCount: 1

image:
  repository: hocikto19/kube-app-manager-webc
  pullPolicy: always
  tag: latest

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: traefik
  annotations: {}
  host: kube-app-manager.example.com
  path: /
  pathType: Prefix
  webEntryPoint: web
  webSecureEntryPoint: websecure
  redirectFromWeb: true
  tls: []

# Usually this should point to the same host as the ingress host, including the /apps path.
appsBackendUrl: ""

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http

readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false

nodeSelector: {}
tolerations: []
affinity: {}
