{{- if and .Values.ingress.enabled .Values.ingress.tls.enabled .Values.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "kube-app-manager-webc.fullname" . }}
  labels:
    {{- include "kube-app-manager-webc.labels" . | nindent 4 }}
spec:
  secretName: {{ include "kube-app-manager-webc.tlsSecretName" . }}
  dnsNames:
    - {{ .Values.ingress.host | quote }}
  issuerRef:
    name: {{ .Values.certManager.issuerRef.name | quote }}
    kind: {{ .Values.certManager.issuerRef.kind | quote }}
    group: {{ .Values.certManager.issuerRef.group | quote }}
{{- end }}